# Generated by Django 2.0 on 2018-01-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duck_konundrum', models.BooleanField(default=False)),
                ('puzzle_in_two_metas', models.BooleanField(default=False)),
                ('two_person_runaround', models.BooleanField(default=False)),
                ('duck_soup_solves', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
